### ISSUE TITLE
Administrative: Removing

### ISSUE THREAD

**Issue by poklj** [withinsoft/ventriloquist#5]
Add the ability to have other users (Preferably ones with a role or a specific Permission) to remove other users proxy targets, Allowing the curbing of undesirable targets or Inappropriate targets

**Comment by Xe** [comment]
![5d3cd921-611d-4b5c-860d-396047995c95](https://user-images.githubusercontent.com/529003/38717186-196d500c-3e9a-11e8-9075-912997703bc1.jpeg)
