### ISSUE TITLE
Administrative: Editing 

### ISSUE THREAD

**Issue by poklj** [withinsoft/ventriloquist#6]
Add the ability to have other users (Preferably ones with a role or a specific Permission) to edit other users Proxy Targets, Be it settings or the actual name of the target

**Comment by Xe** [comment]
![1d6cfc42-6de0-4fe2-b91f-98ffc17ed05c](https://user-images.githubusercontent.com/529003/38717154-c54a821a-3e99-11e8-9cbe-c63b4f46fc74.jpeg)
