### ISSUE TITLE
Administrative: Resetting

### ISSUE THREAD

**Issue by poklj** [withinsoft/ventriloquist#7]
Add the ability to have other users (Preferably ones with a role or a specific Permission) to reset the settings of a Users Target proxies (either all of the proxies or specific proxies).

**Comment by Xe** [comment]
![760fa16f-87a1-4715-8378-a36ebd3556be](https://user-images.githubusercontent.com/529003/38717144-bab611d4-3e99-11e8-957b-24f958b72eca.jpeg)
